### ISSUE TITLE
Similarity function using matchms functionality

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/SpectriPy#11]
This issue is to discuss how to best integrate the spectra similarity functionality from `matchms`.

**Comment by michaelwitting** [comment]
What you want is this:

https://matchms.readthedocs.io/en/latest/api/matchms.Scores.html

There is `calculate_scores` which is similar to `compareSpectra`. It is basically the wrapper for all the differen similarty measures and takes of comparing x against. So we don't need to write any loop or so in Python.

**Comment by jorainer** [comment]
Option A)

@michaelwitting 's suggestion to have `compareSpectra` and define the matching function with `FUN`:

In order for that to work:

- `MAPFUN` needs to be a function that simply returns the peak matrices **without** any mapping.
- `FUN` should then be a function that converts the peak matrices to Python, calculates the similarity in python and returns a single `numeric`.

Advantages:
- *easiest* for the user.
- `Spectra` would take care of the loop, getting the data and generating the resulting matrix.

Disadvantage:
- potentially slow?

**Comment by jorainer** [comment]
Option B)

Let do python do all the dirty work:

- convert the whole `Spectra` into a (python) list of matchms.Spectrum objects.
- Run the full comparison in python (with `calculate_scores` as mentioned above) and return the `matrix`.

Advantage:
- potentially fast (Python loop)

Disadvantage:
- converting the full `Spectra` means we need to load the full data into memory (something that is **not** done in option A)).
- would need a different function than `compareSpectra` as the loop et al is performed in python.

**Comment by jorainer** [comment]
I would actually suggest to implement both options - I'm curious about the performance differences... if Python is much faster we might consider to use in future more of the code from the Python community.

**Comment by jorainer** [comment]
Catching up on my comment on #12: I think the function looks good, only, I think it would be better to use a method with param classes instead. Why? This would allow us to bundle the parameters for each algorithm within the parameter class (and also check there for correct user input), the method would then dispatch on the parameter class and run the respective call in python. This might also simplify to add additional python similarity scores (or ML-based approaches) because we can simply define these via new paramter classes instead having to hack into the `compareSpectriPy` function.

Any thoughts or concerns?

**Comment by michaelwitting** [comment]
I know you like your `param` objects. 👍 
No objections from my side.
