### ISSUE TITLE
Returning error for format_scores.py

### ISSUE THREAD

**Issue by chufz** [rformassspectrometry/SpectriPy#5]
@hechth: When using your suggested file ´format_scores.py´, i reveal the following error:

´´´
Fehler in py_call_impl(callable, dots$args, dots$keywords) : 
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
´´´
see https://github.com/chufz/SpectriPy/blob/caro/examples/example_workflow.R and
https://github.com/chufz/SpectriPy/blob/caro/R/compareSpectripy.R on line #22 for implemetation

**Comment by hechth** [comment]
Is this related to the `id` thing or something different? just to be sure.

**Comment by chufz** [comment]
yes, solved
