### ISSUE TITLE
Create package

### ISSUE THREAD

**Issue by jorainer** [rformassspectrometry/SpectriPy#8]
If OK for you @michaelwitting @chufz @hechth , I would now merge first Michael's PR #6 and would then create/clean the package - eventually also configuring it that the Python dependencies get automatically installed.

**Comment by chufz** [comment]
yes, for sure!

**Comment by michaelwitting** [comment]
Thumbs up!

**Comment by jorainer** [comment]
Seems like we can get around python install routines etc using the [basilisk](https://www.bioconductor.org/packages/release/bioc/html/basilisk.html) package. I will try to configure the package such that all necessary dependencies are installed automatically.
